### ISSUE TITLE
Issue when build

### ISSUE THREAD

**Issue by Merlinkoss** [andreyyurin/VKLight#1]
When I am try to build from master branch - 
FATAL EXCEPTION: main
    Process: ltc.ru.vklight, PID: 28871
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ltc.ru.vklight/ltc.ru.vklight.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to ltc.ru.base.app.ProjectApplication

P.s. Я понимаю, что чисто случайно наткнулся на Ваш проект спустя 18 часов после первого коммита И уже завожу issue, а все это в целом очень странно. Но идея замечательна!

**Comment by andreyyurin** [comment]
> When I am try to build from master branch -
> FATAL EXCEPTION: main
> Process: ltc.ru.vklight, PID: 28871
> java.lang.RuntimeException: Unable to start activity ComponentInfo{ltc.ru.vklight/ltc.ru.vklight.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to ltc.ru.base.app.ProjectApplication
> 
> P.s. Я понимаю, что чисто случайно наткнулся на Ваш проект спустя 18 часов после первого коммита И уже завожу issue, а все это в целом очень странно. Но идея замечательна!

Спасибо за ответ! Проект только начал разрабатывать и могут быть ошибки:)  Ваша ошибка исправлена - пробуйте подгружать из ветки develop, до релиза - основной код будет там
